### ISSUE TITLE
`merquery.generate` mix task ignores `--base_url` option

### ISSUE THREAD

**Issue by olegokunevych** [acalejos/merquery#14]
When running `mix merquery.generate --base_url http://localhost:4000` command, `merquery.livemd` uses default `0.0.0.0` host.

Actual Result:

url is `http://0.0.0.0`

Expected Result:

url is `http://localhost:4000`

At the same time `--out` option works as expected.

**Comment by acalejos** [comment]
This was actually a quirk of OptionParser, where options defined in Elixir with underscored must be passed in t he command line using hyphens. 

So mainly this was a documentation error. Use `--base-url` instead of `--base_url`
