### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by dkuku** [acalejos/merquery#16]
Hey @acalejos. I wanted to play a bit with it but when installing I saw an error:
![Screenshot from 2024-11-27 17-47-53](https://github.com/user-attachments/assets/764fb776-1613-44bb-a339-9f0e0c7f28d4)
Then I see this but I think it's due to the error on compilation:
```
Failed to load the widget JS module, got the following error:

    error loading dynamically imported module: http://localhost:8090/public/sessions/wzg6ynplofxwbcgljniopopbcarbgiovzyna5ktg6gzmjvqt/assets/2qoyzwmpaczaj2mabgmoz6ccpy/main.js

See the browser console for more details. If running behind an authentication proxy, make sure the /public/* routes are publicly accessible.
```

**Comment by acalejos** [comment]
Hey thanks for bringing this to my attention. 

I think I forgot to add the build directory to the mix.exs to tell Hex to upload it. I'll put out a patch here shortly

**Comment by acalejos** [comment]
@dkuku Try now on the 0.2.1 patch

**Comment by dkuku** [comment]
@acalejos It loads now 👍🏻 , thanks
