### ISSUE TITLE
Auth Tab

### ISSUE THREAD

**Issue by acalejos** [acalejos/merquery#6]
Have a separate tab to support common auth schemes using the Req auth option

**Comment by kevinschweikert** [comment]
Would https://github.com/derekkraan/curl_req/pull/10 help?

**Comment by acalejos** [comment]
The plan is to just use the Req `auth` option (https://hexdocs.pm/req/Req.Steps.html#auth/1) so I don't think CurlReq is needed for this feature

**Comment by acalejos** [comment]
Added in 8c353497cc097d9fbfe17d66cba4e5a9e9c76edb

**Comment by kevinschweikert** [comment]
Sorry, I was not clear enough. Would it help if CurlReq parses the auth into the Req.Steps.auth step or wouldn't it make a difference if we just keep the auth headers? That's why I linked to the PR
